name: Get latest libgit2 release version
on:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Fetch release version
        run: |
          mkdir -p release-versions
          curl -sL https://api.github.com/repos/libgit2/libgit2/releases/latest | \
          jq -r ".tag_name" > release-versions/libgit2.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Scott McKendry'
          git config --global user.email '39483124+scottmckendry@users.noreply.github.com'
          git commit -am "chore: new release version"
          git push
